import type { Theme, ThemeId } from '@/types'

export const themes: Record<ThemeId, Theme> = {
  'dark-blue': {
    id: 'dark-blue',
    name: 'Dark Blue',
    emoji: '🌙',
    bg: 'bg-blue-950',
    bgSecondary: 'bg-blue-900',
    text: 'text-blue-50',
    textSecondary: 'text-blue-200',
    accent: 'text-blue-400',
    accentBg: 'bg-blue-500',
    border: 'border-blue-700',
    progressTrack: 'bg-blue-800',
    cardBg: 'bg-blue-900',
  },
  'light-blue': {
    id: 'light-blue',
    name: 'Light Blue',
    emoji: '☀️',
    bg: 'bg-blue-50',
    bgSecondary: 'bg-blue-100',
    text: 'text-blue-950',
    textSecondary: 'text-blue-700',
    accent: 'text-blue-500',
    accentBg: 'bg-blue-500',
    border: 'border-blue-300',
    progressTrack: 'bg-blue-200',
    cardBg: 'bg-blue-100',
  },
  'dark-green': {
    id: 'dark-green',
    name: 'Dark Green',
    emoji: '🌿',
    bg: 'bg-green-950',
    bgSecondary: 'bg-green-900',
    text: 'text-green-50',
    textSecondary: 'text-green-200',
    accent: 'text-green-400',
    accentBg: 'bg-green-500',
    border: 'border-green-700',
    progressTrack: 'bg-green-800',
    cardBg: 'bg-green-900',
  },
  'light-green': {
    id: 'light-green',
    name: 'Light Green',
    emoji: '🍀',
    bg: 'bg-green-50',
    bgSecondary: 'bg-green-100',
    text: 'text-green-950',
    textSecondary: 'text-green-700',
    accent: 'text-green-500',
    accentBg: 'bg-green-500',
    border: 'border-green-300',
    progressTrack: 'bg-green-200',
    cardBg: 'bg-green-100',
  },
  'dark-purple': {
    id: 'dark-purple',
    name: 'Dark Purple',
    emoji: '🎭',
    bg: 'bg-purple-950',
    bgSecondary: 'bg-purple-900',
    text: 'text-purple-50',
    textSecondary: 'text-purple-200',
    accent: 'text-purple-400',
    accentBg: 'bg-purple-500',
    border: 'border-purple-700',
    progressTrack: 'bg-purple-800',
    cardBg: 'bg-purple-900',
  },
  'light-purple': {
    id: 'light-purple',
    name: 'Light Purple',
    emoji: '💜',
    bg: 'bg-purple-50',
    bgSecondary: 'bg-purple-100',
    text: 'text-purple-950',
    textSecondary: 'text-purple-700',
    accent: 'text-purple-500',
    accentBg: 'bg-purple-500',
    border: 'border-purple-300',
    progressTrack: 'bg-purple-200',
    cardBg: 'bg-purple-100',
  },
  'dark-orange': {
    id: 'dark-orange',
    name: 'Dark Orange',
    emoji: '🔥',
    bg: 'bg-orange-950',
    bgSecondary: 'bg-orange-900',
    text: 'text-orange-50',
    textSecondary: 'text-orange-200',
    accent: 'text-orange-400',
    accentBg: 'bg-orange-500',
    border: 'border-orange-700',
    progressTrack: 'bg-orange-800',
    cardBg: 'bg-orange-900',
  },
  'light-orange': {
    id: 'light-orange',
    name: 'Light Orange',
    emoji: '🍊',
    bg: 'bg-orange-50',
    bgSecondary: 'bg-orange-100',
    text: 'text-orange-950',
    textSecondary: 'text-orange-700',
    accent: 'text-orange-500',
    accentBg: 'bg-orange-500',
    border: 'border-orange-300',
    progressTrack: 'bg-orange-200',
    cardBg: 'bg-orange-100',
  },
  'dark-red': {
    id: 'dark-red',
    name: 'Dark Red',
    emoji: '🌅',
    bg: 'bg-red-950',
    bgSecondary: 'bg-red-900',
    text: 'text-red-50',
    textSecondary: 'text-red-200',
    accent: 'text-red-400',
    accentBg: 'bg-red-500',
    border: 'border-red-700',
    progressTrack: 'bg-red-800',
    cardBg: 'bg-red-900',
  },
  'light-red': {
    id: 'light-red',
    name: 'Light Red',
    emoji: '🌹',
    bg: 'bg-red-50',
    bgSecondary: 'bg-red-100',
    text: 'text-red-950',
    textSecondary: 'text-red-700',
    accent: 'text-red-500',
    accentBg: 'bg-red-500',
    border: 'border-red-300',
    progressTrack: 'bg-red-200',
    cardBg: 'bg-red-100',
  },
  'dark-cyan': {
    id: 'dark-cyan',
    name: 'Dark Cyan',
    emoji: '💎',
    bg: 'bg-cyan-950',
    bgSecondary: 'bg-cyan-900',
    text: 'text-cyan-50',
    textSecondary: 'text-cyan-200',
    accent: 'text-cyan-400',
    accentBg: 'bg-cyan-500',
    border: 'border-cyan-700',
    progressTrack: 'bg-cyan-800',
    cardBg: 'bg-cyan-900',
  },
  'light-cyan': {
    id: 'light-cyan',
    name: 'Light Cyan',
    emoji: '💧',
    bg: 'bg-cyan-50',
    bgSecondary: 'bg-cyan-100',
    text: 'text-cyan-950',
    textSecondary: 'text-cyan-700',
    accent: 'text-cyan-600',
    accentBg: 'bg-cyan-500',
    border: 'border-cyan-300',
    progressTrack: 'bg-cyan-200',
    cardBg: 'bg-cyan-100',
  },
  'dark-slate': {
    id: 'dark-slate',
    name: 'Dark Slate',
    emoji: '🏔️',
    bg: 'bg-slate-900',
    bgSecondary: 'bg-slate-800',
    text: 'text-slate-50',
    textSecondary: 'text-slate-300',
    accent: 'text-slate-400',
    accentBg: 'bg-slate-600',
    border: 'border-slate-700',
    progressTrack: 'bg-slate-700',
    cardBg: 'bg-slate-800',
  },
  'light-slate': {
    id: 'light-slate',
    name: 'Light Slate',
    emoji: '☁️',
    bg: 'bg-slate-100',
    bgSecondary: 'bg-slate-200',
    text: 'text-slate-900',
    textSecondary: 'text-slate-600',
    accent: 'text-slate-700',
    accentBg: 'bg-slate-600',
    border: 'border-slate-300',
    progressTrack: 'bg-slate-300',
    cardBg: 'bg-slate-200',
  },
  'light-amber': {
    id: 'light-amber',
    name: 'Light Amber',
    emoji: '✨',
    bg: 'bg-amber-50',
    bgSecondary: 'bg-amber-100',
    text: 'text-amber-950',
    textSecondary: 'text-amber-700',
    accent: 'text-amber-600',
    accentBg: 'bg-amber-500',
    border: 'border-amber-300',
    progressTrack: 'bg-amber-200',
    cardBg: 'bg-amber-100',
  },
}

export const themeList = Object.values(themes)

export const DEFAULT_THEME: ThemeId = 'dark-blue'
